# Jekyll main configuration file

title: fivethirtyfour - nonprofit IT services, small business IT services, enterprise IT services, and web design.
description: "IT services for all."

baseurl: "/"
url: "https://fivethirtyfour.com"

permalink: pretty # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "/articles/page:num/"

plugins:
  - jekyll-paginate # Manually add to Gemfile in Jekyll Plugins
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Socials
personal_twitter: colinrubbert
personal_linkedin: colinrubbert
business_twitter: fivethirtyfour
business_linkedin: fivethirtyfour
