# Jekyll main configuration file

title: fivethirtyfour - IT Services
description: "IT services for all."

baseurl: "/"
url: "https://fivethirtyfour.com"

permalink: date # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

# Build settings
sass:
  style: :nested
markdown: kramdown
permalink: pretty

paginate: 10
paginate_path: "/articles/page:num/"

plugins:
  - jekyll-paginate # Manually add to Gemfile in Jekyll Plugins
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock